title: Waterline Developer Hub
description: WATERLINE Developer Resources - Elevating VR/AR Innovation in Water Education
theme: just-the-docs

logo: "/assets/images/logo.jpeg"

favicon_ico: "/assets/images/favicon.ico"

url: https://waterline-project.github.io

callouts:
  warning:
    title: Warning
    color: red

  highlight:
    title: Highlight
    color: yellow

  important:
    title: Important
    color: blue

  new:
    title: New
    color: green

  note:
    title: Note
    color: purple

